### ISSUE TITLE
Ability to set type attribute on content

### ISSUE THREAD

**Issue by wezm** [vtduncan/rust-atom#6]
It's not possible to set the [type attribute](https://tools.ietf.org/html/rfc4287#section-4.1.3.1) on the content element. This means it isn't possible to embed html in the content as is often done on blogs.

**Comment by wezm** [comment]
I might have a go at adding this. I'm currently thinking something like:

```rust
enum Content {
    Plain(String),
    Html(String),
    Xhtml(String),
}

struct Entry {
    ..
    content: Content,
    ..
}
```

**Comment by vtduncan** [comment]
Hi @wezm, thanks for looking into this! Handling the type attribute properly would be a welcome improvement.

From first glance, it might be difficult to handle the xhtml case as `Xhtml(String)` because RustyXML will parse inside the `<content>` tag and return a tree of elements. Maybe something like `Xhtml(xml::Element)` to just let the XML tree pass through untouched?

Only other nitpick would be to rename `Plain` to `Text` to match the spec as closely as possible. Even though 'text' is a rather lousy and undescriptive word I think there's value in keeping a one-to-one mapping in the naming. :)

**Comment by wezm** [comment]
Ok work is underway in my [entry-content-type](https://github.com/vtduncan/rust-atom/compare/master...wezm:entry-content-type) branch.
